name: Continuous Integration
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "(feat|fix|docs|chore|ci): .+"
          helpMessage: "Example: 'feat: example of title'"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: run linting
        run: npm run lint
      - name: run unit tests
        run: npm run test
      - run: echo "🍏 This job's status is ${{ job.status }}."